# Generated by Django 5.0.7 on 2024-09-16 14:43

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30)),
                ('matric_number', models.CharField(max_length=15)),
                ('institution', models.CharField(choices=[('UI', 'University of Ibadan'), ('FSSOYO', 'Federal School of Surveying, Oyo'), ('EAUEDOYO', 'Emmanuel Alayande University of Education, Oyo')], max_length=8)),
                ('faculty', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=50)),
                ('fingerprint', imagekit.models.fields.ProcessedImageField(upload_to='fingerprints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
