# Generated by Django 5.0.7 on 2024-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='fingerprint',
            field=models.CharField(max_length=50),
        ),
    ]
