# Generated by Django 5.0.7 on 2024-09-16 15:45

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_volunteer_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='fingerprint',
            field=imagekit.models.fields.ProcessedImageField(upload_to='fingerprints/'),
        ),
    ]
