# Generated by Django 5.0.7 on 2024-08-03 11:11

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_participant_remove_progresstracking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fingerprint',
            field=imagekit.models.fields.ProcessedImageField(upload_to='fingerprints/'),
        ),
    ]
