# Generated by Django 5.0.7 on 2024-09-17 06:25

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_volunteer_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='fingerprint',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default_fingerprint.jpg', null=True, upload_to='fingerprints/'),
        ),
    ]
