# Generated by Django 5.1.1 on 2024-10-10 10:00

import imagekit.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participanti',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', imagekit.models.fields.ProcessedImageField(blank=True, default='fingerprints/default_fingerprint.jpg', null=True, upload_to='fingerprints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
