# Generated by Django 5.1.1 on 2024-10-10 10:04

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_participant_delete_participanti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fingerprint',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='fingerprints/default_fingerprint.jpg', null=True, upload_to='fingerprints/participant'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='fingerprint',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='fingerprints/default_fingerprint.jpg', null=True, upload_to='fingerprints/volunteer'),
        ),
    ]
