# Generated by Django 5.1.1 on 2024-10-13 17:43

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_participant_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fingerprint',
            field=imagekit.models.fields.ProcessedImageField(unique=True, upload_to='participants'),
        ),
    ]
