# Generated by Django 5.1.1 on 2024-10-13 17:49

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_participant_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='participants'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
