# Generated by Django 5.1.1 on 2024-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_fingerprint_participant_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image_name',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
